name: Merge develop into main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "skavechain-bot"
        git config user.email "shaun.kavanagh.vechain.bot@gmail.com"
        git fetch --prune --unshallow
        git checkout main
        git config --global credential.helper store
        echo "https://github.com/skavechain-bot/PAT-user-testing.git\nusername=${{ secrets.PAT_BOT_TOKEN }}" > ~/.git-credentials

    - name: Merge develop into main
      run: |
        git merge --no-ff ${{ github.event.before }}

    - name: Push changes
      run: |
        git push origin main

    - name: Clean up
      run: git checkout ${{ github.event.before }}
    
