name: Merge develop into main

on:
  push:
    branches:
      - develop
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PAT_BOT_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "skavechain-bot"
        git config user.email "shaun.kavanagh.vechain.bot@gmail.com"
        git fetch --prune --unshallow
        git checkout main
        git remote set-url origin "https://${{ secrets.PAT_BOT_TOKEN }}@github.com/Skavechain/PAT-user-testing.git"
      
    - name: Debug Git Config
      run: |
        git config --get remote.origin.url
        
    - name: Merge develop into main
      run: |
        git config user.name "skavechain-bot"
        git config user.email "shaun.kavanagh.vechain.bot@gmail.com"
        git merge --no-ff ${{ github.event.before }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Push changes
      run: |
        git config user.name "skavechain-bot"
        git config user.email "shaun.kavanagh.vechain.bot@gmail.com"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Clean up
      run: |
        git checkout ${{ github.event.before }}
    
