# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
permissions: 
    contents: write # This is required for actions/checkout
    pull-requests: write # This is required for pull request comments
jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Check for changes
      run: |
        git fetch origin main
        git checkout main
        git fetch origin develop
        git checkout develop
        changes=$(git rev-list --count main..develop)
        echo "Number of changes between main and develop: $changes"
        if [ "$changes" -eq 0 ]; then
            echo "No changes to merge. Exiting workflow."
            exit 0
        fi
  e2e-test:
    runs-on: ubuntu-latest
    needs: check-for-changes
    steps:
    - name: Run E2E Test
      uses: ./.github/workflows/e2e.yml 

  merge-develop-into-main:
    runs-on: ubuntu-latest
   # needs: e2e-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    
    - name: Checkout main and merge develop
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global credential.helper store
        git fetch origin main
        git fetch origin develop
        git checkout main
        git merge origin/develop --no-ff -m "Merge develop into main - $(date +"%Y-%m-%d %H:%M:%S")"
        git push origin main          
